numBatches: 1
batchSize: 1
queue: e2e-test-queue
jobSetId: job-set-preemptible
jobs:
  - namespace: default
    priority: 0
    podSpec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      priorityClassName: armada-preemptible
      containers:
        - name: sleeper
          image: alpine:latest
          command:
            - sh
          args:
            - -c
            - sleep 600
          resources:
            limits:
              memory: 25Mi
              cpu: 100m
            requests:
              memory: 25Mi
              cpu: 100m
---
action: ACTION_PREEMPT
selection: SELECTION_BY_ID
preemptReason: "Test job preemption for validation"
timeout: "100s"
expectedEvents:
  - submitted:
  - preempted:
